### ISSUE TITLE
Running acceptance tests fails on MacOS 10.8.3

### ISSUE THREAD

**Issue by lc3t35** [SamHatoum/meteor-rtd-example-project#13]
I had a first try with PhantomJS, switched to Chrome after reading issue #11.
Node 0.8.14, meteor 0.6.4

When i run grunt, the acceptance tests fails , here is the log of grunt --debug :
- \- - Running unit tests - - -
  ...........
  Chrome 22.0 (Mac): Executed 11 of 11 SUCCESS (0.061 secs / 0.006 secs)
  [D] Task source: /Users/laurent/dev/meteor/real-time-development-with-meteor/test/rtd/node_modules/grunt-bg-shell/tasks/bg-shell.coffee
  [D] Task source: /Users/laurent/dev/meteor/real-time-development-with-meteor/test/rtd/node_modules/grunt-bg-shell/tasks/bg-shell.coffee
  [D] Task source: /Users/laurent/dev/meteor/real-time-development-with-meteor/test/rtd/node_modules/grunt-bg-shell/tasks/bg-shell.coffee
- \- - Running acceptance tests - - -
  >> timers.js:103
  >>             if (!process.listeners('uncaughtException').length) throw e;
  >>                                                                       ^
  >> UnknownError: unknown error: version info not a dictionary
  >>   (Driver info: chromedriver=0.8,platform=Mac OS X 10.8.3 x86_64) (WARNING: The server did not provide any stacktrace information)
  >> Command duration or timeout: 1.08 seconds
  >> Build info: version: '2.32.0', revision: '6c40c18', time: '2013-04-09 17:22:56'
  >> System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.8.3', java.version: '1.6.0_45'
  >> Driver info: org.openqa.selenium.chrome.ChromeDriver
  >>     at new bot.Error (/Users/laurent/dev/meteor/real-time-development-with-meteor/test/rtd/node_modules/selenium-webdriver/lib/atoms/error.js:108:18)
  >>     at Object.bot.response.checkResponse (/Users/laurent/dev/meteor/real-time-development-with-meteor/test/rtd/node_modules/selenium-webdriver/lib/atoms/response.js:106:9)
  >>     at /Users/laurent/dev/meteor/real-time-development-with-meteor/test/rtd/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:133:20
  >>     at /Users/laurent/dev/meteor/real-time-development-with-meteor/test/rtd/node_modules/selenium-webdriver/lib/goog/base.js:1112:15
  >>     at webdriver.promise.ControlFlow.runInNewFrame_ (/Users/laurent/dev/meteor/real-time-development-with-meteor/test/rtd/node_modules/selenium-webdriver/lib/webdriver/promise.js:1431:20)
  >>     at notify (/Users/laurent/dev/meteor/real-time-development-with-meteor/test/rtd/node_modules/selenium-webdriver/lib/webdriver/promise.js:315:12)
  >>     at notifyAll (/Users/laurent/dev/meteor/real-time-development-with-meteor/test/rtd/node_modules/selenium-webdriver/lib/webdriver/promise.js:284:7)
  >>     at fulfill (/Users/laurent/dev/meteor/real-time-development-with-meteor/test/rtd/node_modules/selenium-webdriver/lib/webdriver/promise.js:389:7)
  >>     at /Users/laurent/dev/meteor/real-time-development-with-meteor/test/rtd/node_modules/selenium-webdriver/lib/webdriver/promise.js:600:51
  >>     at /Users/laurent/dev/meteor/real-time-development-with-meteor/test/rtd/node_modules/selenium-webdriver/lib/webdriver/http/http.js:96:5
  >> ==== async task ====
  >> WebDriver.createSession()
  >>     at Function.webdriver.WebDriver.acquireSession_ (/Users/laurent/dev/meteor/real-time-development-with-meteor/test/rtd/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:131:49)
  >>     at Function.webdriver.WebDriver.createSession (/Users/laurent/dev/meteor/real-time-development-with-meteor/test/rtd/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:110:30)
  >>     at Builder.build (/Users/laurent/dev/meteor/real-time-development-with-meteor/test/rtd/node_modules/selenium-webdriver/builder.js:70:22)
  >>     at module.exports (/Users/laurent/dev/meteor/real-time-development-with-meteor/test/rtd/webdrivers/selenium-server.js:14:17)
  >>     at reuseOrCreateSession (/Users/laurent/dev/meteor/real-time-development-with-meteor/test/acceptance/leaderboard.spec.js:53:69)
  >>     at Request.getWebdriverSessions [as _callback](/Users/laurent/dev/meteor/real-time-development-with-meteor/test/acceptance/leaderboard.spec.js:21:13)
  >>     at Request.init.self.callback (/Users/laurent/dev/meteor/real-time-development-with-meteor/test/rtd/node_modules/request/index.js:148:22)
  >>     at Request.EventEmitter.emit (events.js:99:17)
  >>     at Request.onResponse (/Users/laurent/dev/meteor/real-time-development-with-meteor/test/rtd/node_modules/request/index.js:876:14)
  Fatal error: 
  timers.js:103
          if (!process.listeners('uncaughtException').length) throw e;
                                                                    ^
  UnknownError: unknown error: version info not a dictionary
  (Driver info: chromedriver=0.8,platform=Mac OS X 10.8.3 x86_64) (WARNING: The server did not provide any stacktrace information)
  Command duration or timeout: 1.08 seconds
  Build info: version: '2.32.0', revision: '6c40c18', time: '2013-04-09 17:22:56'
  System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.8.3', java.version: '1.6.0_45'
  Driver info: org.openqa.selenium.chrome.ChromeDriver
  at new bot.Error (/Users/laurent/dev/meteor/real-time-development-with-meteor/test/rtd/node_modules/selenium-webdriver/lib/atoms/error.js:108:18)
  at Object.bot.response.checkResponse (/Users/laurent/dev/meteor/real-time-development-with-meteor/test/rtd/node_modules/selenium-webdriver/lib/atoms/response.js:106:9)
  at /Users/laurent/dev/meteor/real-time-development-with-meteor/test/rtd/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:133:20
  at /Users/laurent/dev/meteor/real-time-development-with-meteor/test/rtd/node_modules/selenium-webdriver/lib/goog/base.js:1112:15
  at webdriver.promise.ControlFlow.runInNewFrame_ (/Users/laurent/dev/meteor/real-time-development-with-meteor/test/rtd/node_modules/selenium-webdriver/lib/webdriver/promise.js:1431:20)
  at notify (/Users/laurent/dev/meteor/real-time-development-with-meteor/test/rtd/node_modules/selenium-webdriver/lib/webdriver/promise.js:315:12)
  at notifyAll (/Users/laurent/dev/meteor/real-time-development-with-meteor/test/rtd/node_modules/selenium-webdriver/lib/webdriver/promise.js:284:7)
  at fulfill (/Users/laurent/dev/meteor/real-time-development-with-meteor/test/rtd/node_modules/selenium-webdriver/lib/webdriver/promise.js:389:7)
  at /Users/laurent/dev/meteor/real-time-development-with-meteor/test/rtd/node_modules/selenium-webdriver/lib/webdriver/promise.js:600:51
  at /Users/laurent/dev/meteor/real-time-development-with-meteor/test/rtd/node_modules/selenium-webdriver/lib/webdriver/http/http.js:96:5
  ==== async task ====
  WebDriver.createSession()
  at Function.webdriver.WebDriver.acquireSession_ (/Users/laurent/dev/meteor/real-time-development-with-meteor/test/rtd/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:131:49)
  at Function.webdriver.WebDriver.createSession (/Users/laurent/dev/meteor/real-time-development-with-meteor/test/rtd/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:110:30)
  at Builder.build (/Users/laurent/dev/meteor/real-time-development-with-meteor/test/rtd/node_modules/selenium-webdriver/builder.js:70:22)
  at module.exports (/Users/laurent/dev/meteor/real-time-development-with-meteor/test/rtd/webdrivers/selenium-server.js:14:17)
  at reuseOrCreateSession (/Users/laurent/dev/meteor/real-time-development-with-meteor/test/acceptance/leaderboard.spec.js:53:69)
  at Request.getWebdriverSessions [as _callback](/Users/laurent/dev/meteor/real-time-development-with-meteor/test/acceptance/leaderboard.spec.js:21:13)
  at Request.init.self.callback (/Users/laurent/dev/meteor/real-time-development-with-meteor/test/rtd/node_modules/request/index.js:148:22)
  at Request.EventEmitter.emit (events.js:99:17)
  at Request.onResponse (/Users/laurent/dev/meteor/real-time-development-with-meteor/test/rtd/node_modules/request/index.js:876:14)

**Comment by xolvio** [comment]
Try going here http://localhost:4444/wd/hub and create a new session with chrome and with firefox. Does that work?

**Comment by lc3t35** [comment]
i can create a session with chrome and with firefox. And then ?

**Comment by lc3t35** [comment]
clean install -> problem is now here https://github.com/xolvio/rtd/issues/27
